import { CASSETTE_RECORDING_CALIBRATION_PLUGIN, CASSETTE_RECORDING_CALIBRATION_PLUGIN_ID } from "./CassetteRecordingCalibrationPlugin.jsx";
import { PLAYER_PROFILE_WORKBENCH_PLUGIN, PLAYER_PROFILE_WORKBENCH_PLUGIN_ID } from "./PlayerProfileWorkbenchPlugin.jsx";

export const TOOL_PLUGINS = [
  CASSETTE_RECORDING_CALIBRATION_PLUGIN,
  PLAYER_PROFILE_WORKBENCH_PLUGIN,
];

export { CASSETTE_RECORDING_CALIBRATION_PLUGIN_ID };
export { PLAYER_PROFILE_WORKBENCH_PLUGIN_ID };
