import { CASSETTE_RECORDING_CALIBRATION_PLUGIN, CASSETTE_RECORDING_CALIBRATION_PLUGIN_ID } from "./CassetteRecordingCalibrationPlugin.jsx";

export const TOOL_PLUGINS = [
  CASSETTE_RECORDING_CALIBRATION_PLUGIN,
];

export { CASSETTE_RECORDING_CALIBRATION_PLUGIN_ID };
