export const STANDARD_SAMPLE_RATE = 48000;
export const DEFAULT_GRID_MIN_HZ = 20;
export const DEFAULT_GRID_MAX_HZ = 20000;
export const DEFAULT_POINTS_PER_OCTAVE = 24;
export const DEFAULT_ANCHOR_RANGE_HZ = [500, 2000];

export const PROFILE_TYPE = "side.player-listening-profile";
export const PROFILE_VERSION = 1;

export const PROBE_SYNC_MIN_SCORE = 0.65;
export const PROGRAM_ALIGN_MIN_SCORE = 0.55;
export const CONFIDENCE_MIN_USABLE = 0.35;
export const FIT_SCORE_PASS = 0.8;
export const FIT_SCORE_WARN = 0.65;

export const PROBE_KIND = "probe-v1";
export const PROGRAM_KIND = "program-v1";

export const PROBE_ESS_START_HZ = 20;
export const PROBE_ESS_END_HZ = 20000;
export const PROBE_ESS_DURATION_SEC = 16.0;
export const PROBE_SYNC_DURATION_SEC = 0.25;
export const PROBE_GAP_SEC = 0.08;
export const PROBE_PRE_SILENCE_SEC = 0.3;
export const PROBE_POST_SILENCE_SEC = 0.3;
export const PROBE_AMPLITUDE = 0.72;

export const PROGRAM_FRAME_SIZE = 4096;
export const PROGRAM_HOP_SIZE = 1024;
export const PROGRAM_MIN_TRACK_COVERAGE = 0.75;
export const PROGRAM_MIN_TRACK_MID_CONFIDENCE = 0.7;
export const PROGRAM_MIN_USABLE_BAND_HZ = [60, 12000];

export const WORKBENCH_ERROR = {
  PROBE_SYNC_FAILED: "PROBE_SYNC_FAILED",
  PROBE_SEGMENT_MISSING: "PROBE_SEGMENT_MISSING",
  PROBE_BANDWIDTH_TOO_NARROW: "PROBE_BANDWIDTH_TOO_NARROW",
  PROGRAM_NO_TRACK_PAIRS: "PROGRAM_NO_TRACK_PAIRS",
  PROGRAM_ALIGN_FAILED: "PROGRAM_ALIGN_FAILED",
  PROGRAM_INSUFFICIENT_COVERAGE: "PROGRAM_INSUFFICIENT_COVERAGE",
  PROGRAM_NO_VALID_TRACKS: "PROGRAM_NO_VALID_TRACKS",
  EQ_MODEL_INVALID_BANDS: "EQ_MODEL_INVALID_BANDS",
  EQ_MODEL_INVALID_BASIS: "EQ_MODEL_INVALID_BASIS",
  COMPILER_MISSING_EQ_MODEL: "COMPILER_MISSING_EQ_MODEL",
  COMPILER_INCOMPATIBLE_PROFILES: "COMPILER_INCOMPATIBLE_PROFILES",
  COMPILER_FIT_TOO_LOW: "COMPILER_FIT_TOO_LOW",
};

export const PROFILE_ERROR = {
  INVALID_JSON: "INVALID_JSON",
  INVALID_SCHEMA: "INVALID_SCHEMA",
  INVALID_GRID: "INVALID_GRID",
  INVALID_ANCHOR: "INVALID_ANCHOR",
  INVALID_EQ_MODEL: "INVALID_EQ_MODEL",
  MISSING_EQ_MODEL: "MISSING_EQ_MODEL",
};
